ai:
  dashscope:
    api-key: your-apikey
    model: modelName
    base-url: https://dashscope.aliyuncs.com/compatible-mode/v1

weather:
  api:
    api-key: your-weather-apikey

serper:
  api-key: your-serper-apikey